### ISSUE TITLE
createVrmlFromString can not do with proto node

### ISSUE THREAD

**Issue by cgdog1970** [create3000/x_ite#101]
**Describe the bug**
I can use Browser.createVrmlFromString(str) with standard node, but wrong with proto node.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/86223006/154785286-42b6a9ff-a4e4-4bf1-898d-c5245703adaa.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]window 7/32bit
 - Browser [e.g. chrome, safari]360安全浏览器13 base by Google ChromiumBSD
 - Version [e.g. 22]13.1.5188.0

**Smartphone (please complete the following information):**

**Additional context**
`PROTO	table [
#	eventOut	MFNode addChildren
]
{
	Group	{children [
		Transform {translation 0 0.5 0
			children [
				Shape	{appearance Appearance {material Material {}} geometry Cylinder {radius 0.1 height 1}}
			]
		}
		Transform {translation 0 1.02 0
			children [
				Shape	{appearance Appearance {material Material {}} geometry Box {size 1 0.04 1}}
			]
		}
	]}
}
#table	{}

#Shape	{geometry Box {}}
#Transform	{translation 0 1.2 0 children [table {}]}

DEF ROOT Group{children[]}
Script {
	field	SFString str "table{}"
#	field	SFString str " Shape	{geometry Box {}} "
	field SFNode ROOT USE ROOT 
#	directOutput TRUE
	url	"vrmlscript:
	function initialize(){
		print (str);
		new_f = new MFNode();
		new_f = Browser.createVrmlFromString(str);
		ROOT.addChildren = new_f;
	}	
	"
}
`

**Comment by create3000** [comment]
I cannot reproduce the bug. I used your source code:

```js
PROTO table [

eventOut MFNode addChildren

]
{
Group {children [
Transform {translation 0 0.5 0
children [
Shape {appearance Appearance {material Material {}} geometry Cylinder {radius 0.1 height 1}}
]
}
Transform {translation 0 1.02 0
children [
Shape {appearance Appearance {material Material {}} geometry Box {size 1 0.04 1}}
]
}
]}
}
#table {}

#Shape {geometry Box {}}
#Transform {translation 0 1.2 0 children [table {}]}

DEF ROOT Group{children[]}
Script {
field SFString str "table{}"

field SFString str " Shape {geometry Box {}} "

field SFNode ROOT USE ROOT 
directOutput TRUE

url	"vrmlscript:
function initialize(){
	print (str);
	new_f = new MFNode();
	new_f = Browser.createVrmlFromString(str);
	ROOT.addChildren = new_f;
}	
"
}
```

Everything works fine, it creates a `Box`. I notices that you specified two times a field named `str` in the Script node 'ROOT', this results in the last one used, which is 'Shape {geometry Box {}}' and not 'table{}'.

**Comment by create3000** [comment]
If you want to create the proto in VRML, you must declare the proto within the string, but I recommend to use X3D instead of VRML.

To use X3D save your file as .x3dv, and then you can use in the Script node the X3D function `Browser.currentScene.createProto("table")`.

See also:
https://create3000.github.io/x_ite/reference/ECMAScript-Object-and-Function-Definitions.html
https://create3000.github.io/x_ite/reference/Scene-Services.html

**Comment by create3000** [comment]
I also notices that you doesn't use `const` or `let`, or at least `var` to declare a variable in JavaScript. This is not recommended, because you do pollute the global namespace, where already a lot of standard JavaScript variables are defined. You should do something like this:

```js
let new_f = "bah";
```

See also: https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/

**Comment by cgdog1970** [comment]
str="Shape {geometry Box {}}" for standard node,createVrmlFromString(str) work right.
str="table{}" for proto node table defined before,but not run right.
you can note # str="Shape {geometry Box {}}" line,only use str="table{}" test again，you will get wrong.
I use X3D node in VRML work well but createVrmlFromString except

**Comment by create3000** [comment]
Simply to use `createVrmlFromString("table{}")` will not work and that's intentional. What will work is if you include the proto within the code string like that `createVrmlFromString("PROTO table [] {} table{}")`. But I highly recommend using X3D `scene.createProto`, there should be no reason why. VRML is of 1997, and that's long ago. X3D is standardized as well, and provides a rich set of nodes and functionality.

**Comment by cgdog1970** [comment]
Thank you very much. createVrmlFromString(str) -- str include proto definition can do well.
 I use VRML work many years with blaxxun and  find can use X3D node like LayerSet in VRML format with xite -- It is great work! 
So, I think 'createVrmlFromString' can do like blaxxun with VRML format.  It seems I must study more Javascript with X3D.
