### ISSUE TITLE
Capture rendered image from <x3d-canvas> element with JavaScript

### ISSUE THREAD

**Issue by fkievith** [create3000/x_ite#106]
I would like to capture snapshots of the rendered image from the X3DCanvas with JavaScript. To be clear I only would like the rendered image of the scene, so not the context menu overlay if that one is active. I tried to capture the image from the embedded <canvas> element by using `.toDataURL()`, but that results only in a black image with the size of the canvas. So probably capturing the image should be done in the same event as where the buffer is rendered.

Maybe it's not in scope of the X_ITE X3D Browser, but I would really appreciate If their would be a way to capture the rendered image from the canvas element.

**Comment by create3000** [comment]
This is possible if you set the attribute _preserveDrawingBuffer_ of the X3DCanvas element to `true`, see https://create3000.github.io/x_ite/#preservedrawingbuffer. You then must look for the real `canvas` element inside the X3DCanvas. With jQuery it would look like this:

```js
const
   canvas = $("X3DCanvas") .find ("canvas") .get (0),
   image  = canvas .toDataURL ("image/png");

```

**Comment by fkievith** [comment]
Thanks! This solved it. I should have read the docs better.

**Comment by create3000** [comment]
I finally added the desired functions to the X3DBrowser reference. The example from above will now look like this:

```js
const 
   Browser = X3D .getBrowser (),
   image   = Browser .toDataURL ("image/png");
```

The functions available on \<canvas\> element are now part of X3DBrowser and documented here: https://create3000.github.io/x_ite/reference/browser-services#mediastream-capturestream-number-framerate-non-standard.

Think this is a better solution then adding a cavas property. I will release a new version tomorrow or so.

**Comment by create3000** [comment]
@splace Cool looks good. Nice simulation. But get an error when pressing the record button.

**Comment by splace** [comment]
@create3000

> @splace Cool looks good. Nice simulation. But get an error when pressing the record button.

recording now working again, firefox+chromium

broken due to the actual canvas being a child, and changing location. was kinda waiting/hoping for the x3d node to BE a canvas (prototyped with), like now it is? i guess, much simpler for this.

the simulation world itself has a fairly general purpose dynamics engine, was from what was going to be a suite of educational stuff, gave up with this due to browser incompatibility/non-compliant behaviour (no expectation to have a user install the one browser that worked.). FYI its 18 years old!
