### ISSUE TITLE
x_ite as a Maven or Gradle dependency

### ISSUE THREAD

**Issue by VijayGatla** [create3000/x_ite#110]
**Additional context**
Is there a way to add x_ite as a Maven or Gradel dependency in Java based projects.

**Comment by create3000** [comment]
I do not know much about Java. You know that X_ITE is JavaScript not Java, isn't it. I googled around Maven and NPM and found this link https://stackoverflow.com/questions/56983025/how-to-use-a-npm-package-as-a-maven-dependency.

**Comment by VijayGatla** [comment]
@create3000, thank you for the quick response.

X3DOM is available as a maven dependency on https://www.webjars.org/

two reference pictures:
> https://drive.google.com/file/d/19gPEho04QXafJQitSLCP9yaLckS8QDhK
> https://drive.google.com/file/d/1sUGY0LczNbvtf4lqLbYoQlZIQw5W94fH

I was wondering, if it could also be possible with X_ITE, on webjars.
thanks.

**Comment by create3000** [comment]
Have now added the latest version 4.7.15 to the WebJars index. Hopefully the package is right and works for you. The interesting files are in the `dist` folder. Please let me know.

In the future you should be able to add a new or older version of X_ITE for you own by pressing the "Add a WebJar" button next to the search field at https://www.webjars.org/. Then select WebJar Type:  NPM (because X_ITE is also available via NPM), package name "x_ite" and select a version, then press "Deploy".  That's all. Have fun.

**Comment by create3000** [comment]
Because everyone can add a WebJar from X_ITE at https://www.webjars.org/, I will close this issue now.
