### ISSUE TITLE
Support for JPG image format?

### ISSUE THREAD

**Issue by brutzman** [create3000/x_ite#38]
The following scene doesn't render the .jpg image in the second LOD child. Not sure why.

http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter03Grouping/LODIndex.html
http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter03Grouping/LODX_ITE.html
http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter03Grouping/LOD.jpg

Related
18.2.2 Texture map image formats
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texturing.html#TextureMapImageFormats

Thanks for all efforts!

**Comment by create3000** [comment]
In general this scene works fine and the image is also loaded and rendered, but X_ITE used extended lit colour and alpha mapping (http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/lighting.html#t-Unlitcolourandalpha) where  Irgb = ITrgb × Drgb (RGB texture and Color node NULL). This mean the Material node's diffuseColour is always multiplied with the texture color. And because there is a Material with a difffuseColor 0 0 0, it results in a black rendered image. Removing the Material node or setting the diffuseColor to 1 1 1 would solve the problem.

**Comment by splace** [comment]
the file specifies diffuseColor 0 0 0, removing it, to get the default, fixes it.

this behaviour, and the fix, the same in view3dscene.

**Comment by splace** [comment]
[info] another faulty conformance test...

http://www.web3d.org/x3d/content/ConformanceNist/Miscellaneous/EXTERNPROTO/first_protoIndex.html

described as green sphere being correct behaviour, actually should be blue, making x_ite right.

**Comment by brutzman** [comment]
both problems are now fixed
